### PR TITLE
Add 404 handling from ResourceServiceGetIamPolicy

### PR DESCRIPTION
**Pull request by pmmukh**
### :hammer_and_wrench: Add 404 handling from ResourceServiceGetIamPolicy

- Currently, when we try to create a binding or policy on an HVS App that doesn't have any policy associated with it, the ResourceServiceGetIamPolicy done to fetch the existing call errors out, which bubbles up as an error in the terraform apply. 
- This PR adds handling for the 404 error in this case, to ignore it and allow the subsequent PUT call to proceed
- Also updates the docs to be under HCP Vault Secrets and fixes an example in one of them
### :building_construction: Acceptance tests

- [ ] Are there any feature flags that are required to use this functionality?
- [ ] Have you added an acceptance test for the functionality being added?
- [ ] Have you run the acceptance tests on this branch?

Output from acceptance testing:

```sh
$ make testacc TESTARGS='-run=TestAccXXX'

...
```

### CODE REVIEW

**Comment by manish-hashicorp** [comment]
Looks good!

**Review by codergs — APPROVED** [review]
LGTM, I am not sure if Cloud Platform wants to own these docs or not, but I will assume this is the best categorization.

**Comment by pmmukh** [comment]
Yeap so this recategorization and putting the docs into the HVS folder was recommended from platform, and I imagine going forward it will be the service team i.e us, that owns this long term.

**Review by manish-hashicorp — APPROVED** [review]
Looks good

**Pull request merged**
