### PR TITLE
Revert "Add support for http observability on vault_cluster resource"

### PR DESCRIPTION
**Pull request by jaireddjawed**
Reverts hashicorp/terraform-provider-hcp#660 because there is a bug that makes http_uri required when an audit_log_config is provided.

### CODE REVIEW

**Comment by mercedesbh** [comment]
@jaireddjawed Looks like a changelog check failure

**Comment by himran92** [comment]
@jaireddjawed @mercedesbh  just for context: have we clarified with terraform team around any concerns with reverts?

**Comment by mercedesbh** [comment]
@himran92 There's some discussion now in[ this thread](https://hashicorp.slack.com/archives/C05BBTQFCGZ/p1697822256416009).

**Comment by aidan-mundy** [comment]
Please remove the changelog from this PR, it is not needed. You can bypass the changelog check using the pr/no-changelog tag.

There should not be any concerns with reverting since this code has not yet released in a provider version.

**Review by aidan-mundy — CHANGES_REQUESTED** [review]
Please remove the changelog from this PR, it is not needed. Also make sure the old changelog is removed by this revert. 

You can bypass the changelog check using the pr/no-changelog tag.

There should not be any concerns with reverting since this code has not yet released in a provider version.

**Review by aidan-mundy — APPROVED** [review]

**Pull request merged**
