### PR TITLE
Upgrade from Protocol 5 to 6

### PR DESCRIPTION
**Pull request by dadgar**
### :hammer_and_wrench: Description

Upgrade from Protocol 5 to 6. I was going to add a nested block and noticed the documentation recommends against it and instead to use nested attribute types which are only available on protocol 6.

https://developer.hashicorp.com/terraform/plugin/framework/handling-data/blocks/single-nested

### :building_construction: Acceptance tests

- [X] Are there any feature flags that are required to use this functionality?
- [ ] Have you added an acceptance test for the functionality being added?
- [X] Have you run the acceptance tests on this branch?

### CODE REVIEW

**Review by aidan-mundy — CHANGES_REQUESTED** [review]
Mostly looks good. 

Need to update the providersdkv2 tests to use V6 Protos. This should also include manual migration testing as per the migration guide for TF Mux/TF Framework. 
Need to update documentation to reflect changes to minimum terraform version. 
We should also release a preemptive version with a deprecation notice to indicate that older terraform versions will no longer be supported in a few weeks time. Not sure if there is a way for us to detect old tf versions and output a warning, or if we'll just have to depreciate via changelog notice.

**Comment by dadgar** [comment]
@aidan-mundy Thanks for the review!

> Need to update the providersdkv2 tests to use V6 Protos. This should also include manual migration testing as per the migration guide for TF Mux/TF Framework.

Done! I am running https://github.com/hashicorp/terraform-provider-hcp/actions/runs/6540633820 to conduct the integration tests.

> Need to update documentation to reflect changes to minimum terraform version.

[Done.](https://github.com/hashicorp/terraform-provider-hcp/pull/637/commits/80608e274ffd64bef562b1abe80bd68c43ad03c8) 

> We should also release a preemptive version with a deprecation notice to indicate that older terraform versions will no longer be supported in a few weeks time. Not sure if there is a way for us to detect old tf versions and output a warning, or if we'll just have to depreciate via changelog notice.

Sure thing! https://github.com/hashicorp/terraform-provider-hcp/pull/638

**Review by AnPucel — COMMENTED** [review]
Looks great! Thanks for doing this. It was on our list after implementing the muxer. I think just running the acceptance test workflow in the CI would be helpful as well. And I think as @aidan-mundy mentioned some manual migration tests if we wanna be thorough. I believe I did one per product on the initial muxer changes.

**Review by aidan-mundy — APPROVED** [review]
Updates look great! For the manual migration testing, I'd check with @AnPucel for some help on the best way to do it.

LGTM (in around 2 weeks haha)

**Comment by himran92** [comment]
thanks for the changes. 
cc: oncall @aoripov 
i am going to approve as acceptance tests are passed.

**Comment by himran92** [comment]
> thanks for the changes. cc: oncall @aoripov i am going to approve as acceptance tests are passed.

**Review by himran92 — APPROVED** [review]

**Review by manish-hashicorp — APPROVED** [review]

**Review by NickCellino — APPROVED** [review]

**Review by dmalch-hashicorp — APPROVED** [review]

**Review by uruemu — APPROVED** [review]

**Comment by dadgar** [comment]
Manually tested the migration: https://gist.github.com/dadgar/7b4d5393d6453701b82fe72ac802102f

**Review by manish-hashicorp — APPROVED** [review]

**Review by ohm — APPROVED** [review]

**Pull request merged**
