### PR TITLE
VAULT-18334: Documentation Subcategories

### PR DESCRIPTION
**Pull request by dhuckins**
### :hammer_and_wrench: Description

Updating docs to use sub-categories

- resources/data-sources that already had templates were updated
- resources/data-sources that did not have a template, had a template created

| Name | Subcategory |
| ------ | ------------ |
| hcp_aws_network_peering | HashiCorp Virtual Networks | 
| hcp_aws_transit_gateway_attachment | HashiCorp Virtual Networks | 
| hcp_azure_peering_connection | HashiCorp Virtual Networks | 
| hcp_boundary_cluster | HCP Boundary | 
| hcp_consul_agent_helm_config | HCP Consul | 
| hcp_consul_agent_kubernetes_secret | HCP Consul | 
| hcp_consul_cluster | HCP Consul | 
| hcp_consul_cluster_root_token | HCP Consul | 
| hcp_consul_snapshot | HCP Consul | 
| hcp_consul_versions | HCP Consul | 
| hcp_hvn | HashiCorp Virtual Networks | 
| hcp_hvn_peering_connection | HashiCorp Virtual Networks | 
| hcp_hvn_route | HashiCorp Virtual Networks | 
| hcp_packer_bucket_names | HCP Packer | 
| hcp_packer_channel | HCP Packer | 
| hcp_packer_channel_assignment | HCP Packer | 
| hcp_packer_image | HCP Packer | 
| hcp_packer_image_iteration | HCP Packer | 
| hcp_packer_iteration | HCP Packer | 
| hcp_packer_run_task | HCP Packer | 
| hcp_vault_cluster | HCP Vault | 
| hcp_vault_cluster_admin_token | HCP Vault | 
| hcp_vault_secrets_app | HCP Vault Secrets |

### CODE REVIEW

**Review by AnPucel — APPROVED** [review]

**Review by aidan-mundy — APPROVED** [review]
LGTM!

I'd be interested to see if there is a way to automate this better, especially with the new folder structure for Framework-written resources/datasources that will mirror the categories used here.

**Review by manish-hashicorp — APPROVED** [review]

**Comment by AnPucel** [comment]
Just a small thing. I'm seeing the data sources for Vault Secrets, but not the resources for Vault Secrets in here.

**Review by uruemu — APPROVED** [review]

**Review by riddhi89 — APPROVED** [review]
LGTM

**Comment by dhuckins** [comment]
> Just a small thing. I'm seeing the data sources for Vault Secrets, but not the resources for Vault Secrets in here.

nice catch!

**Review by hashiblaum — APPROVED** [review]

**Review by jaireddjawed — APPROVED** [review]
LGTM

**Pull request merged**
